n1 = int(5)
n2 = int(2)
print('+', n1+n2)
print('-', n1-n2)
print('*', n1*n2)
print('/', n1/n2)
print('Potência: **', n1**n2)
print('Divisão Inteira: //', n1//n2)
print('Resto da divisão: %', n1%n2) 
